---
version: "3"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: lynuslyell/react-dev-image
    ports:
      - "4000:3006"
    volumes:
      - /app/node_modules
      - .:/app
    
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: lynuslyell/react-dev-image
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm","run","test"]